data:
  batch_size: 448
  cond_args:
    in_bias_arr: 0
    in_norm_arr: 1
    out_bias_arr: 0
    out_norm_arr: 1
  data_file: hippo_aerosol_training_data.nc
  data_path: /glade/derecho/scratch/mhayman/aerosol/datasets/
  input_cols: []
  output_cols:
  - number_concentration
  - mean_r
  test_fraction: 0.05
  train_fraction: 0.7
  valid_fraction: 0.25
  wavelength_inputs:
    backscatter_coefficient:
      wavelength_lst:
      - 1.064e-06
      - 5.32e-07
      - 3.55e-07
    extinction_coefficient:
      wavelength_lst:
      - 1.064e-06
      - 5.32e-07
      - 3.55e-07
model:
  dtype: float64
  int_count: 1000
  layer_count: 4
  layer_nodes: 540
  polynomial_order_1: 28
  polynomial_order_2: 24
save_loc: /glade/derecho/scratch/mhayman/aerosol_poly_nn/echo/
trainer:
  amp: false
  batches_per_epoch: 512
  grad_accum_every: 1
  learning_rate: 0.001493288076204095
  max_epochs: 1500
  scheduler:
    factor: 0.1
    min_lr: 1.0e-08
    patience: 100
    threshold: 2.2821148028414207e-05
  stopping_patience: 6
  valid_batches_per_epoch: 64
