
data:
  input_cols: ['backscatter_coefficient', 'extinction_coefficient']
  output_cols: ['number_concentration', 'mean_r']
  train_fraction: 0.9
  valid_fraction: 0.05
  test_fraction: 0.05
  batch_size: 256

model:
  layer_lst: [512, 1024, 1024, 512]
  polynomial_order_1: 21
  polynomial_order_2: 21
  int_count: 1000


training:
  learning_rate: 1.0e-4
  max_epochs: 1500
  



