
save_loc: "/glade/derecho/scratch/mhayman/aerosol_poly_nn/beta6_alpha2_r_eff_13_02/"

data:
  data_path: "/glade/derecho/scratch/mhayman/aerosol/datasets/"  
  data_file: "hippo_aerosol_index_training_data_train.nc"
  valid_data_path: "/glade/derecho/scratch/mhayman/aerosol/datasets/"
  valid_data_file: "hippo_aerosol_index_training_data_valid.nc"
  test_data_path: "/glade/derecho/scratch/mhayman/aerosol/datasets/"
  test_data_file: "hippo_aerosol_index_training_data_test.nc"
  wavelength_inputs:
    backscatter_coefficient:
      wavelength_lst: [1064.0e-9, 710.0e-9, 800.0e-9, 532.0e-9, 400.0e-9, 355.0e-9,] # [1064e-9, 710e-9, 800e-9, 532e-9, 400e-9, 355e-9,]
      real_index_lst: [1.3, 1.3, 1.3, 1.3, 1.3, 1.3,]
      imag_index_lst: [0.02, 0.02, 0.02, 0.02, 0.02, 0.02,]
    extinction_coefficient:
      wavelength_lst: [532.0e-9, 355.0e-9] # [1064.0e-9, 532.0e-9, 355.0e-9]
      real_index_lst: [1.3, 1.3,]
      imag_index_lst: [0.02, 0.02,]

  input_cols: []
  output_cols: ['number_concentration', 'effective_r']
  train_fraction: 0.7
  valid_fraction: 0.25
  test_fraction: 0.05
  batch_size: 256
  cond_args:
    in_norm_arr: 1
    in_bias_arr: 0
    out_norm_arr: 1
    out_bias_arr: 0

model:
  dtype: 'float64'
  layer_count: 4
  layer_nodes: 512
  # layer_lst: [512, 1024, 1024, 512]
  polynomial_order_1: 40 # 21
  polynomial_order_2: 40 # 21
  int_count: 1000


trainer:
  batches_per_epoch: 512
  valid_batches_per_epoch: 256
  grad_accum_every: 1
  amp: false
  learning_rate: 1.0e-4
  max_epochs: 50
  stopping_patience: 3
  scheduler:
    threshold: 1.0e-4
    factor: 0.1
    patience: 2
    min_lr: 1.0e-8
  



